# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - DoomsdayAlgorithm

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_5a89db358cf04ceb82bbd8047b00d6b4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e66e55c6ed0c46ef8ee5da21e16192f2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5a89db358cf04ceb82bbd8047b00d6b4 }}/doomsday:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'DoomsdayAlgorithm'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fbeae7df20f641d8ab82ccc61ea4d003 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5a89db358cf04ceb82bbd8047b00d6b4 }}/doomsday:${{ github.sha }}'